deploy master:
  script:
  - "#Se setea el home (estaba dando error)"
  - export HOME=/root
  - "#Se crea .capistrano/metrics para que no pregunte si desea guardar estadisticas"
  - mkdir .capistrano
  - touch .capistrano/metrics
  - cd config/capistrano
  - cap master deploy;
  type: deploy
  tags: 
  only:
  - master
deploy development:
  script:
  - "#Se setea el home (estaba dando error)"
  - export HOME=/root
  - "#Se crea .capistrano/metrics para que no pregunte si desea guardar estadisticas"
  - mkdir .capistrano
  - touch .capistrano/metrics
  - cd config/capistrano
  - cap development deploy;
  type: deploy
  tags:
  only:
  - development

