image: docker:git
services:
- docker:dind

stages:
- deploy

deploy development:
  image: gitlab.4geeks.co:4567/devops/runner4runer:capistrano
  script:
  - cd config/capistrano
  - cap development deploy
  tags:
  - deploy
  only:
  - development
  stage: deploy

deploy master:
  image: gitlab.4geeks.co:4567/devops/runner4runer:capistrano
  script:
  - cd config/capistrano
  - cap master deploy
  tags:
  - deploy
  only:
  - master
  stage: deploy
